# Generated by Django 2.2.14 on 2020-08-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20200805_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launched', models.IntegerField(default=0)),
                ('add_date', models.DateField(auto_now=True)),
                ('book_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'wish',
            },
        ),
        migrations.AlterModelTable(
            name='userbook',
            table='userbook',
        ),
    ]
