# Generated by Django 2.2.14 on 2020-08-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20200805_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=128)),
                ('message', models.TextField()),
                ('mobile', models.CharField(max_length=11)),
                ('isbn', models.CharField(max_length=30)),
                ('book_name', models.CharField(max_length=64)),
                ('book_author', models.CharField(max_length=64)),
                ('book_img', models.ImageField(upload_to='')),
                ('requester_id', models.IntegerField()),
                ('requester_nickname', models.CharField(max_length=32)),
                ('gifter_id', models.IntegerField()),
                ('gift_id', models.IntegerField()),
                ('gifter_nickname', models.CharField(max_length=32)),
                ('status', models.IntegerField(default=0)),
                ('add_date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'drift',
            },
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launched', models.IntegerField(default=0)),
                ('add_date', models.DateField(auto_now=True)),
                ('book_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'gift',
            },
        ),
    ]
