# Generated by Django 2.2.14 on 2020-08-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_drift_gift'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='nickname',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='wish',
            name='nickname',
            field=models.CharField(default='', max_length=32),
        ),
    ]
