# Generated by Django 2.2.14 on 2020-08-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20200805_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='nickname',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='wish',
            name='nickname',
            field=models.CharField(max_length=32),
        ),
    ]
